[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/intro"
  to = "/.netlify/functions/intro"
  status = 200

[[redirects]]
  from = "/api/sheet"
  to = "/.netlify/functions/sheet"
  status = 200

[[redirects]]
  from = "/api/leaderboard"
  to = "/.netlify/functions/leaderboard"
  status = 200

[functions."leaderboard-snapshot"]
  schedule = "*/15 * * * *"
